### ISSUE TITLE
Add Mozilla floating point exception handler to libcx in the same way exceptq was added.

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/libcx#56]

**Comment by dmik** [comment]
Yes, that definitely makes sense and was actually already planned by me for Qt, see: https://github.com/bitwiseworks/qtbase-os2/issues/22#issuecomment-404845427. Thanks for popping it up here.

**Comment by dmik** [comment]
Just installing the Mozilla-(NSPR-)like exception handler from LIBCx works like a charm in case of `tst_QLocale` in Qt 5 (see https://github.com/bitwiseworks/qtbase-os2/issues/29#issuecomment-442226987). However, this approach blindly restores the entier set of MCW_EM bits and may break the application if it calls `__control87` to fine tune teh FPU control word to its own needs (and e.g. deliberately unmasks some of exceptions).

Since LIBCx is a global solution, I decided to go further and support such cases. This is relatively easy. I will intercept all `_control87` kLIBC calls to grab the current value and then simply restore it in the exception handler if it differs from what was grabbed last time. And we will even let the exception go if it was unmasked with `_control87`. This will be an ultimate solution that doesn't require any user setup.

**Comment by dmik** [comment]
I've done the ultimate solution but found some small problem. Restoring the FPU CW in the exception handler and continuing execution doesn't entirely restore the FPU behavior. E.g. if we mask out the divide by zero interrupt, the FPU should put `NaN` into the result but it doesn't do that for some reason, it places zero instead. Some programs may freak out.

More over, I can't get the default FPU processing back even after `_fpreset` and `_clear87`. I'm confused. Somehow a single exception screws it.

Note that this strange behavior has always been there in Mozilla or in any other app (like cairo) using the system exception handler to recover from these failures.

**Comment by dmik** [comment]
Did some further debugging. It was actually the optimizer that'd make all other divisions return 0 instead of `Inf`. Declaring variables as `volatile` solves that. There is still a problem with the first failed operation (the one after which we restore the FPU CW). Since this operation has already been processed by the FPU by the time the exception occurs, it will not fill the result with the proper value even if we continue execution. I came up with two possible solutions to that:

1. The obvious one: emulate the FPU behavior and put the right value (`Inf`, `NaN` etc) ourselves.
2. The tricky one (hey, me!): rewind to the previous instruction, i.e. the one that caused an exception within the FPU, before continuing execution.

Obviously, the solution no. 2 is the most elegant one. However, in order to do that, we need to know the exact size of the previous CPU instruction. This is not a trivial task but I found a nice solution here: https://github.com/greenbender/lend. It's small so pretty much OK to be incorporated into LIBCx.

Note that I now recall that I could decide to go with the wrapper mode instead of the exception handler mode in Qt 4 (see https://github.com/bitwiseworks/qtbase-os2/issues/22 for details) because I faced some case where having a correct result after continuing execution was vital. I don't have a proof but given that I've already found a solution, I think this is not important. I will implement it tomorrow and this will give us a solid behavior as if Gpi/Win calls would have never screwed the FPU CW up.

**Comment by dryeo** [comment]
On 11/29/18 03:25 PM, Dmitriy Kuminov wrote:
> Note that this strange behavior has always been there in Mozilla or in
> any other app (like cairo) using the system exception handler to recover
> from these failures.

Actually only under Warp v4.5+. Used to be able to pass all kinds of FPU 
tests on Warp V4 that failed on eCS without patching

**Comment by dmik** [comment]
Really? Okay, good to know. However, I more meant that the workaround applied in Mozilla would leave zero in the result instead of `Inf`/`NaN` and it could have negative consequences somewhere.

**Comment by dmik** [comment]
All done. Works quite well here. I guess we should now remove the Mozilla-like FPU exception handler in all places where it is used to let LIBCx do its work.

**Comment by dmik** [comment]
I'm reopening this as by a suggestion from Steven Levine I found that there the complete FPU state record (available in the CONTEXT record inside the exception handler) actually contains an "Instruction Pointer" value at offset 12 (in bytes) which is set to the instruction that caused the exception. I didn't know that. I did some checks and now I see that this is exactly what I need. No disassembly is necessary therefore. I will redo this part.

This is a good piece of info about the FPU internals: http://www.website.masmforum.com/tutorials/fptute/index.html. The description of the FPU state record is here: http://www.website.masmforum.com/tutorials/fptute/fpuchap3.htm (check the FSAVE / FNSAVE instruction). And Intel references confirm that (e.g. here http://www.c-jump.com/CIS77/reference/Intel/CIS77_24319002/pg_0174.htm).

**Comment by dmik** [comment]
I have to reopen this again. I had some more discussion with @StevenLevine about the current logic of the handler and modified it a bit according to the discussion. However, my current version of it causes `tst_QMetaType` crash with like this:
```

______________________________________________________________________

 Exception Report - created 2018/12/26 19:44:10
______________________________________________________________________

 OS2/eCS Version:  2.45
 # of Processors:  4
 Physical Memory:  3260 mb
 Virt Addr Limit:  1536 mb
 Exceptq Version:  7.11.3-shl (Jul  5 2016)

______________________________________________________________________

 Exception C0000097 - Float Invalid Operation
______________________________________________________________________

 Process:  D:\CODING\QT5\QT5-DEV-BUILD\QTBASE\TESTS\AUTO\CORELIB\KERNEL\QMETATYPE\DEBUG\TST_QMETATYPE.EXE (12/26/2018 15:34:28 5,785,060)
 PID:      8657 (34391)
 TID:      01 (1)
 Priority: 200

 Filename: D:\CODING\QT5\QT5-DEV-BUILD\QTBASE\LIB\QT5CORED.DLL (12/26/2018 01:19:29 36,130,524)
 Address:  005B:1D436E80 (0001:00106E80)

______________________________________________________________________

 Failing Instruction
______________________________________________________________________

 1D436E71  MOV   [ESP+0x4], ESI          (897424 04)
 1D436E75  LEA   EAX, [EBP-0x34]         (8d45 cc)
 1D436E78  MOV   [ESP], EAX              (890424)
 1D436E7B  CALL  0x1d529508              (e8 88260f00)
 1D436E80 >FSTP  QWORD [EBP-0x50]        (dd5d b0)
 1D436E83  MOVSD XMM0, QWORD [EBP-0x50]  (f20f1045 b0)
 1D436E88  MOVSD QWORD [ESP], XMM0       (f20f110424)
 1D436E8D  CALL  0x1d3583b5              (e8 2315f2ff)

______________________________________________________________________

 Registers
______________________________________________________________________

 EAX : 0097F154   EBX  : 0097F600   ECX : 00000047   EDX  : 0097F1E0
 ESI : 0097F1E0   EDI  : 0097F1CF
 ESP : 0097F120   EBP  : 0097F188   EIP : 1D436E80   EFLG : 00010246
 CS  : 005B       CSLIM: FFFFFFFF   SS  : 0053       SSLIM: FFFFFFFF

 EAX : read/write memory on this thread's stack
 EBX : read/write memory on this thread's stack
 ECX : not a valid address
 EDX : read/write memory on this thread's stack
 ESI : read/write memory on this thread's stack
 EDI : read/write memory on this thread's stack

______________________________________________________________________

 Floating Point Context
______________________________________________________________________

 Status  : 8081 - Busy TOP=0 ES  I  Control : 037F - RC=0 PC=2 PM UM OM ZM DM IM
 Tags    : FFFF
 CS:EIP  : 005B:1D529183  Opcode : 0540  DS:Offset : 0053:0097F160

 st(0) fpreg[0] empty : FFFF 0000000000000000
 st(1) fpreg[1] empty : FFFF 0000000000000000
 st(2) fpreg[2] empty : 4002 A000000000000000
 st(3) fpreg[3] empty : 4004 F000000000000000
 st(4) fpreg[4] empty : 4002 9CCCCCCCCCCCD000
 st(5) fpreg[5] empty : 4002 9CCCCCCCCCCCD000
 st(6) fpreg[6] empty : 3FD7 8CBCCC096F508800
 st(7) fpreg[7] empty : 0000 0000000000000000

______________________________________________________________________

 Stack Info for Thread 01
______________________________________________________________________

   Size       Base        ESP         Max         Top
 00800000   00980000 -> 0097F120 -> 0097C000 -> 00180000

______________________________________________________________________

 Call Stack
______________________________________________________________________

   EBP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 Trap  ->  1D436E80   QT5CORED  0001:00106E80  qlocale_tools.cpp#322 __Z13asciiToDoublePKciRbRi16TrailingJunkMode + 16D 0001:00106D13 (D:\Coding\qt5\qt5\qtbase\src\corelib\tools\qlocale_tools.cpp)

  Offset Name                 Type                         Hex Value
  ÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ ÄÄÄÄÄÄÄÄÄ
   8     num                  8 bit unsigned               97F1E0
   12    numLen               32 bit signed                5
   16    ok                   0xD57                        97F1CF
   20    processed            0xD58                        97F1D0
   24    trailingJunkMode     0xD5E                        0
  -36    conv                 0xD60                        7FF40000
  -48    d                    64 bit real                  0.000000
```
Seems to be one of the cases Steven warned me about: when the "retry" operation is too far from the crashing point. I need to account for that.

**Comment by dmik** [comment]
I've read Chapters 4.9, 8.6 and 8.7 from [Intel® 64 and IA-32 Architectures Software Developer’s Manual, Volume 1: Basic Architecture](https://software.intel.com/sites/default/files/managed/a4/60/253665-sdm-vol-1.pdf) (thanks @StevenLevine for the link).

The conclusion is as follows. In general, the faulty FPU instruction may not be safely retried because FPU exceptions are not reported immediately. They are not reported until the next FPU instruction or WAIT/FWAIT (it's a bit more complex but idea is like that). And if the faulty FPU instruction is not immediately followed by another FPU instruction or WAIT/FWAIT, then other instructions which are in between could change the operands of the faulty instruction as well as the general program state. This situation is described in Chapter 8.6 X87 FPU EXCEPTION SYNCHRONIZATION.

So I came with the following idea: we only retry the faulty FPU instruction if it immediately precedes the faulting address (i.e. the place where our exception handler kicks in). In all other cases we simply continue execution from the faulty address hoping that no recovery (retry) was necessary in this particular case. This seems to work on a range of my tests (the LIBCx test and Qt).

We will come up with other work arounds if we find places where this approach still breaks execution. Though, I think that chances to find them are really low given that the previous approach which never retried, didn't show any problems so far (even in cases where FDIV would result in 0 instead of Inf).
