### ISSUE TITLE
_lmalloc doesn't seem to exist in umalloc.h

### ISSUE THREAD

**Issue by Greggk** [bitwiseworks/libcx#59]
Hi

I read the following from the readme.md but _lmalloc and _hmalloc aren't present in umalloc.h. I have the libc-devel 0.6.6-38 and libcx-devel 0.6.3 installed.  What am I missing? I am using pBuffer = (char*)_umalloc(_um_regular_heap, 65000); but don't know if that is correct. It hasn't trapped but the trap was always intermittent. Thanks

Note that regardless of where the regular C heap is placed, the application may access any of the specific heaps at any time with the respective kLIBC API calls from <umalloc.h> (i.e. _lmalloc will always allocate from the low memory heap while _hmalloc will allocate from the high memory heap when high memory is available). This is the recommended way to allocate memory if the application knows exactly which kind of memory it needs (low memory is in particular needed for calling some native OS/2 APIs that don't support high memory and don't have SafeDos* wrappers in <os2safe.h>, and also to communicate to OS/2 device drivers). It is also possible to override the type of the regular heap for the current thread by setting a desired heap with the _udefault function -- this will work regardless of the mode forced by LIBCx.

**Comment by dmik** [comment]
@Greggk it should be `<emx/umalloc.h` (fixed). `_hmalloc` and `_lmalloc` are in fact shortcuts to `_umalloc(_um_high_heap)` and `_umalloc(_um_low_heap)`, respectively. And what you do is basically equivalent to just `malloc` because `_um_regular_heap` is the heap LIBC uses in `malloc` and everywhere else by default which is either high or low depending on `-Zhigh-mem` and voting.
