### ISSUE TITLE
closing of stdin might give an error

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libcx#60]
when a app closes stdin with fclose() the app might send a message like couldn't close stdin: bad file number. see also http://trac.netlabs.org/ports/ticket/145 for more reference

**Comment by dmik** [comment]
This problem is really strange. As reports and my own tests show, removing LIBCx from the linked DLLs make those apps work right. An example is building a `whois` RPM package from its spec file. If `sed` is linked against LIBCx, you get this:
```
Checking for unpackaged file(s): /@unixroot/usr/lib/rpm/check-files D:/Users/dmik/rpmbuild/BUILDROOT/whois-5.4.0-1.i386
sed: couldn't close stdout: Bad file number
```
However, if you rebuild `sed` with no LIBCx linked, the error disappears.

I also tried to disable every kLIBC override in LIBCx so that it just forwards everything to kLIBC w/o running any its own code (at DLL export level) — but it still fails. And `sed` actually doesn't use a single bit from LIBCx even if they are not disabled (except the init code that sets the EXCEPTQ exception handler and such but this is disabled when forwarded to kLIBC). The only explanation that comes to my mind is that linking `sed` against LIBCx changes some timings at application termination and this somehow influences how fast the handles are closed.

Note that as I say in  http://trac.netlabs.org/ports/ticket/145, the problem only shows up when it's a standard handle (0, 1, 2) redirected so that it is connected to a socket pair created by the OS/2 TCP/IP stack. So maybe due to changed timings, it turns out that the other end of this pipe gets closed a tiny bit before `sed` issues its close request and hence the result is EBADF (which is known to be returned by the OS/2 TCP/IP stack when the other end of the pipe gets off the radar).

Note also that the EBADF error comes not from kLIBC itself — I specifically checked this. From the kLIBC point of view, the handle is perfectly fine (an internal structure for it still exists). It's only the underlying `DosClose` that fails.

Note also that another strange thing is that the address of the internal kLIBC struct for the failed handle differs in case of a failure. By default, the standard three handles are allocated at startup and have addresses something like this:
```
162a206c 01 shared.c:327:shared_init: done
162a206e 01 shared.c:1082:fclose: fildes 0 0x184488f0 0
162a206e 01 shared.c:1087:fclose: rc 0 0
162a206e 01 shared.c:1082:fclose: fildes 1 0x18448910 0
162a206e 01 shared.c:1087:fclose: rc 0 0
162a206e 01 shared.c:1082:fclose: fildes 2 0x18448930 0
162a206e 01 shared.c:1087:fclose: rc 0 0
```
However in the failed scenarion fildes 1 gets a higher value:
```
162a44cb 01 shared.c:1082:fclose: fildes 0 0x184488f0 0
162a44cb 01 shared.c:1087:fclose: rc 0 0
162a44cb 01 shared.c:1082:fclose: fildes 1 0x20032600 0
162a44cb 01 shared.c:1087:fclose: rc -1 9
```
IIRC the kLIBC code, the only reason that might explain this is when some special handle inheritance takes place between two kLIBC processes (the one that starts `sed` and `sed` itself in this case). May be it has something to do with some kLIBC inheritance bits. Anyway, it's too complex.

**Comment by dmik** [comment]
I have one idea that I need to check but if it leads to nowhere, I will provide a generic workaround at LIBCx level: intercept all close/fclose calls and ignore EBADF if all of this is troe:

- this is a standard handle 0, 1, 2 and
- it's a valid kLIBC file handle (has an internal struct)
- it is not connected to the console (i.e. was redirected to some file/pipe)

**Comment by dmik** [comment]
A workaround here in LIBCx or in any app is not needed as I believe I fixed it in kLIBC, check the above comment. With that, I'm closing this as the problem doesn't appear any more. It should also fix all cases mentioned in http://trac.netlabs.org/ports/ticket/145 and we should probably revert http://trac.netlabs.org/ports/changeset/2048 one day.
